POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzEwOWM3NGI5MWY0NDQxNjYwYzY2NGEiLCJpYXQiOjE2NjIwMzM3NzV9.MV2Fxq9mJ1aOb6bxPBkkKlgKXk18CZU7wtvUnMCQfQ4

{
    "title": "Blogster",
    "author": "Joel",
    "url": "www.blog.com",
    "likes": 23,
    "userId": "63108da366acccec5eb12588"
}